## 2.1数据无量纲化

In [1]:
from sklearn.preprocessing import MinMaxScaler
data = [[-1,2],[-0.5,6],[0,10],[1,18]]

In [2]:
import pandas as pd
pd.DataFrame(data)

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [3]:
# 实现归一化
scaler = MinMaxScaler()  #实例化
scaler = scaler.fit(data) #fit,在这里本质上是生成min(x)和max(x)
result = scaler.transform(data)#通过接口导出结果，计算公式
result

array([[ 0.  ,  0.  ],
       [ 0.25,  0.25],
       [ 0.5 ,  0.5 ],
       [ 1.  ,  1.  ]])

In [4]:
# scaler.fit_transform(data)可以实现上面两句代码的结果
result_ = scaler.fit_transform(data)#训练和导出结果一步达成
result_

array([[ 0.  ,  0.  ],
       [ 0.25,  0.25],
       [ 0.5 ,  0.5 ],
       [ 1.  ,  1.  ]])

In [5]:
data_ = scaler.inverse_transform(result)#将归一化后的结果逆转
data_

array([[ -1. ,   2. ],
       [ -0.5,   6. ],
       [  0. ,  10. ],
       [  1. ,  18. ]])

也可以使用MinMaxScaler的参数feature_range实现将数据归一化到[0，1]以外的范围内

In [6]:
data = [[-1,2],[-0.5,6],[0,10],[1,18]]
scaler = MinMaxScaler(feature_range=[5,10])#依然实例化
result2 = scaler.fit_transform(data)
result2

array([[  5.  ,   5.  ],
       [  6.25,   6.25],
       [  7.5 ,   7.5 ],
       [ 10.  ,  10.  ]])

当x中的特征数量非常多的时候，fit会报错表示，数据量太大了计算不了了。此时使用partial_fit作为训练接口
scaler = scaler.partial_fit(data)

## BONUS(添加):使用numpy来实现归一化

In [7]:
import numpy as np
x = np.array([[-1,2],[-0.5,6],[0,10],[1,18]])
# 归一化
x_nor = (x-x.min(axis=0))/(x.max(axis=0)-x.min(axis=0))
x_nor

array([[ 0.  ,  0.  ],
       [ 0.25,  0.25],
       [ 0.5 ,  0.5 ],
       [ 1.  ,  1.  ]])

In [8]:
# 逆转归一化
x_returned = x_nor*(x.max(axis=0)-x.min(axis=0))+x.min(axis=0)
x_returned

array([[ -1. ,   2. ],
       [ -0.5,   6. ],
       [  0. ,  10. ],
       [  1. ,  18. ]])

Preprocessing.StandardScaler--数据标准化

In [9]:
from sklearn.preprocessing import StandardScaler
data = [[-1,2],[-0.5,6],[0,10],[1,18]]

In [10]:
scaler = StandardScaler() #实例化
scaler.fit(data)          #fit,本质是生成均值和方差
# 下面这句话有问题
# print("mean:{}".farmat(scaler.mean_),"var:{}".format(scaler.var_))    #查看均值的属性mean_,#查看方差的属性var_   

StandardScaler(copy=True, with_mean=True, with_std=True)

In [11]:
scaler.mean_

array([-0.125,  9.   ])

In [12]:
scaler.var_

array([  0.546875,  35.      ])

In [13]:
x_std = scaler.transform(data)   # 通过接口导出结果
# print("mean:{}".farmat(x_std.mean()),"std:{}".format(x_std.std())) 

In [14]:
x_std.mean()

0.0

In [15]:
x_std.std()

1.0

In [16]:
### scaler.fit_transform(data)  同之前的介绍
### scaler.inverse_transform(x_std)

## 2.2 缺失值的处理

In [1]:
import pandas as pd
data1 = pd.read_csv("E:/ivy_machine_learning/program/莫烦学习/2019年寒假学习+sklearn+jupyter用法/菜菜sklearn完整版/Narrativedata.csv"
                   ,engine='python'
                   ,index_col=0
                   )
# engine='python'这个参数必须有(OSError: Initializing from file failed)---见https://blog.csdn.net/qq_35318838/article/details/80564938
data1.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [7]:
data1.shape

(891, 4)

直接采用python的读法，在我们可视化看来不够清楚，pandas就有很友好的界面显示

In [4]:
f = open("E:/ivy_machine_learning/program/莫烦学习/2019年寒假学习+sklearn+jupyter用法/菜菜sklearn完整版/Narrativedata.csv",'r')
for line in f:
    print(line)

,Age,Sex,Embarked,Survived

0,22.0,male,S,No

1,38.0,female,C,Yes

2,26.0,female,S,Yes

3,35.0,female,S,Yes

4,35.0,male,S,No

5,,male,Q,No

6,54.0,male,S,No

7,2.0,male,S,No

8,27.0,female,S,Yes

9,14.0,female,C,Yes

10,4.0,female,S,Unknown

11,58.0,female,S,Yes

12,20.0,male,S,No

13,39.0,male,S,No

14,14.0,female,S,No

15,55.0,female,S,Unknown

16,2.0,male,Q,No

17,,male,S,Yes

18,31.0,female,S,No

19,,female,C,Yes

20,35.0,male,S,Unknown

21,34.0,male,S,Yes

22,15.0,female,Q,Yes

23,28.0,male,S,Yes

24,8.0,female,S,No

25,38.0,female,S,Unknown

26,,male,C,No

27,19.0,male,S,No

28,,female,Q,Yes

29,,male,S,No

30,40.0,male,C,No

31,,female,C,Yes

32,,female,Q,Yes

33,66.0,male,S,No

34,28.0,male,C,No

35,42.0,male,S,No

36,,male,C,Yes

37,21.0,male,S,No

38,18.0,female,S,No

39,14.0,female,C,Yes

40,40.0,female,S,No

41,27.0,female,S,No

42,,male,C,No

43,3.0,female,C,Unknown

44,19.0,female,Q,Yes

45,,male,S,No

46,,male,Q,No

47,,female,Q,Yes

48,,male,C,No

49,18.0,female,S,No



In [5]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
Age         714 non-null float64
Sex         891 non-null object
Embarked    889 non-null object
Survived    891 non-null object
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


从上面的信息看来，我们存在缺失值。总共数据891

In [6]:
data1.describe()#由于sex,embarked和survived是文本类，所以没办法得到他的统计学特性

Age
count  714.000000
mean    29.699118
std     14.526497
min      0.420000
25%     20.125000
50%     28.000000
75%     38.000000
max     80.000000

impute.simpleImputer
class sklearn.impute.SimpleImputer(missing_values=nan,strategy='mean',fill_value=None,verbose=0,copy=Ture)

data1.loc[:,"Age"]  # 取出"Age"的dataframe,带索引
data1.loc[:,"Age"].values  #取出"Age"的值,无索引，就是一个array

data1.loc[行名称，列名称]
data1.iloc[行索引，列索引]

data1.loc[:,"Age"]  等价于   data1.iloc[:,0]

In [8]:
#填补年龄
Age = data1.iloc[:,0].values.reshape(-1,1)#sklearn要求特征矩阵必须大于等于二维
Age[:20]# 缺失值是nan

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.],
       [nan],
       [54.],
       [ 2.],
       [27.],
       [14.],
       [ 4.],
       [58.],
       [20.],
       [39.],
       [14.],
       [55.],
       [ 2.],
       [nan],
       [31.],
       [nan]])

In [9]:
#有空值，我们要填补
from sklearn.preprocessing import Imputer

In [11]:
from sklearn.impute import SimpleImputer#发现我们存在impute这个模块

In [13]:
imp_mean = SimpleImputer(strategy="mean") #实例化，默认是均值填补
imp_median = SimpleImputer(strategy="median")#中位数填补
imp_frequent = SimpleImputer(strategy="most_frequent")
imp_0 = SimpleImputer(strategy="constant",fill_value=0)#用0填补

In [21]:
help(Imputer)

Help on class Imputer in module sklearn.preprocessing.imputation:

class Imputer(sklearn.base.BaseEstimator, sklearn.base.TransformerMixin)
 |  Imputation transformer for completing missing values.
 |  
 |  Read more in the :ref:`User Guide <imputation>`.
 |  
 |  Parameters
 |  ----------
 |  missing_values : integer or "NaN", optional (default="NaN")
 |      The placeholder for the missing values. All occurrences of
 |      `missing_values` will be imputed. For missing values encoded as np.nan,
 |      use the string value "NaN".
 |  
 |  strategy : string, optional (default="mean")
 |      The imputation strategy.
 |  
 |      - If "mean", then replace missing values using the mean along
 |        the axis.
 |      - If "median", then replace missing values using the median along
 |        the axis.
 |      - If "most_frequent", then replace missing using the most frequent
 |        value along the axis.
 |  
 |  axis : integer, optional (default=0)
 |      The axis along which to i

In [14]:
imp_mean = imp_mean.fit_transform(Age)
imp_median = imp_median.fit_transform(Age)
imp_frequent = imp_frequent.fit_transform(Age)
imp_0 = imp_0.fit_transform(Age)

In [15]:
imp_mean[:20]  #用均值补

array([[22.        ],
       [38.        ],
       [26.        ],
       [35.        ],
       [35.        ],
       [29.69911765],
       [54.        ],
       [ 2.        ],
       [27.        ],
       [14.        ],
       [ 4.        ],
       [58.        ],
       [20.        ],
       [39.        ],
       [14.        ],
       [55.        ],
       [ 2.        ],
       [29.69911765],
       [31.        ],
       [29.69911765]])

In [16]:
imp_median[:20]  #用中位数

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.],
       [28.],
       [54.],
       [ 2.],
       [27.],
       [14.],
       [ 4.],
       [58.],
       [20.],
       [39.],
       [14.],
       [55.],
       [ 2.],
       [28.],
       [31.],
       [28.]])

In [19]:
imp_frequent[:20] #用众数

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.],
       [24.],
       [54.],
       [ 2.],
       [27.],
       [14.],
       [ 4.],
       [58.],
       [20.],
       [39.],
       [14.],
       [55.],
       [ 2.],
       [24.],
       [31.],
       [24.]])

In [18]:
# 这里我们使用中位数来填补Age
data1.iloc[:,0] = imp_median
data1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
Age         891 non-null float64
Sex         891 non-null object
Embarked    889 non-null object
Survived    891 non-null object
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [20]:
#使用众数填补Embarked
Embarked = data1.iloc[:,2].values.reshape(-1,1)
Embarked[:20]  # 缺失值是nan

array([['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['C']], dtype=object)

In [21]:
data1.iloc[:,2] = SimpleImputer(strategy="most_frequent").fit_transform(Embarked)
# data1.info()

In [22]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
Age         891 non-null float64
Sex         891 non-null object
Embarked    891 non-null object
Survived    891 non-null object
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


## BONUS:用pandas和numpy进行填补其实更加简单

In [17]:
import pandas as pd
data1 = pd.read_csv(r"C:\Users\qqw\Desktop\sklearn-机器学习\Narrativedata.csv"
                   ,engine='python'
                   ,index_col=0
                   )
data1.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [18]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
Age         714 non-null float64
Sex         891 non-null object
Embarked    889 non-null object
Survived    891 non-null object
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [19]:
data1.loc[:,"Age"] = data1.loc[:,"Age"].fillna(data1.loc[:,"Age"].median())
#.fillna在Dtaframe里面直接进行填补
data1.dropna(axis=0,inplace=True)
#.dropna(axis=0)删除所有缺失值的行，.dropna(axis=1)删除所有缺失值的列
#参数inplace，为True表示在原数据上修改，为False表示生成一个复制对象，不修改源数据，默认False

In [20]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 4 columns):
Age         889 non-null float64
Sex         889 non-null object
Embarked    889 non-null object
Survived    889 non-null object
dtypes: float64(1), object(3)
memory usage: 34.7+ KB


In [21]:
data1.loc[:,"Embarked"] = data1.loc[:,"Embarked"].fillna(data1.loc[:,"Embarked"].mode())
#.fillna在Dataframe里面直接进行填补
data1.dropna(axis=0,inplace=True)

In [22]:
data1.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [23]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 4 columns):
Age         889 non-null float64
Sex         889 non-null object
Embarked    889 non-null object
Survived    889 non-null object
dtypes: float64(1), object(3)
memory usage: 34.7+ KB


In [23]:
data1.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [24]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
Age         891 non-null float64
Sex         891 non-null object
Embarked    891 non-null object
Survived    891 non-null object
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


# 2.3处理分类型特征：编码与哑变量

preprocessing.labelEncoder:标签专用，能够将分类转换为分类数值

In [25]:
y = data1.iloc[:,3]#要输入的是标签，不是特征矩阵，所以允许一维
y.head()

0     No
1    Yes
2    Yes
3    Yes
4     No
Name: Survived, dtype: object

In [27]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder().fit_transform(y)
# label.inverse_transeform(label) #使用inverse_transform可以逆转
label

array([0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 1, 2, 0, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       2, 2, 0, 1, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 1,
       2, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 0, 0, 0, 2,
       2, 0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 1, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0, 1, 0,
       0, 2, 0, 0, 2, 0, 0, 0, 1, 1, 2, 0, 0, 0, 2, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 0, 0,
       1, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 2, 1, 2, 1, 0, 0, 2, 2, 0, 2, 0,
       2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1, 0, 2, 2, 2, 2, 2, 0, 2, 0, 1,
       0, 0, 1, 2, 2, 1, 0, 2, 2, 0, 2, 2, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0,
       2, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2,

In [28]:
data1.iloc[:,-1] = label#让标签等于我们运行出来的结果
data1.head()

Age     Sex Embarked  Survived
0  22.0    male        S         0
1  38.0  female        C         2
2  26.0  female        S         2
3  35.0  female        S         2
4  35.0    male        S         0

In [38]:
le = LabelEncoder()
le = le.fit(y)
label = le.transform(y)

le.classes_

特征部分，我们也希望其是数值型的，所以引入：preprocessing.OrdinalEncoder：特征专用，能够将分类特征（文本）转为分类数值

In [29]:
from sklearn.preprocessing import OrdinalEncoder

In [30]:
#接口categories_对应LabelEncoder的接口classes_,一模一样的功能
data_ = data1.copy()
data_.head()
# 我们想要sex:male and female-->0,1   embarked:S,C,Q-->0,1,2

Age     Sex Embarked  Survived
0  22.0    male        S         0
1  38.0  female        C         2
2  26.0  female        S         2
3  35.0  female        S         2
4  35.0    male        S         0

In [32]:
data_.iloc[:,1:3]  #取出sex和Embarked这两列有文本的特征

Sex Embarked
0      male        S
1    female        C
2    female        S
3    female        S
4      male        S
5      male        Q
6      male        S
7      male        S
8    female        S
9    female        C
10   female        S
11   female        S
12     male        S
13     male        S
14   female        S
15   female        S
16     male        Q
17     male        S
18   female        S
19   female        C
20     male        S
21     male        S
22   female        Q
23     male        S
24   female        S
25   female        S
26     male        C
27     male        S
28   female        Q
29     male        S
..      ...      ...
861    male        S
862  female        S
863  female        S
864    male        S
865  female        S
866  female        C
867    male        S
868    male        S
869    male        S
870    male        S
871  female        S
872    male        S
873    male        S
874  female        C
875  female        C
876    male        S
877    male        S
878    male        S
879  female        C
880  female        S
881    male        S
882  female        S
883    male        S
884    male        S
885  female        Q
886    male        S
887  female        S
888  female        S
889    male        C
890    male        Q

[891 rows x 2 columns]

In [33]:
# OrdinalEncoder().fit(data_.iloc[:,1:-1]).categories_
data_.iloc[:,1:3] = OrdinalEncoder().fit_transform(data_.iloc[:,1:-1])

data_.head()#现在将特征和标签都转换为了数值类型

Age  Sex  Embarked  Survived
0  22.0  1.0       2.0         0
1  38.0  0.0       0.0         2
2  26.0  0.0       2.0         2
3  35.0  0.0       2.0         2
4  35.0  1.0       2.0         0

In [50]:
data1_ = data1.copy()
data1_.head()

Age     Sex Embarked  Survived
0  22.0    male        S         0
1  38.0  female        C         2
2  26.0  female        S         2
3  35.0  female        S         2
4  35.0    male        S         0

In [51]:
feature = OrdinalEncoder()
feature = feature.fit(data1_.iloc[:,1:-1])
feature_ = feature.transform(data1_.iloc[:,1:-1])
feature.categories_

[array(['female', 'male'], dtype=object), array(['C', 'Q', 'S'], dtype=object)]

In [52]:
data1_.iloc[:,1:-1] = feature_
data1_.head()

Age  Sex  Embarked  Survived
0  22.0  1.0       2.0         0
1  38.0  0.0       0.0         2
2  26.0  0.0       2.0         2
3  35.0  0.0       2.0         2
4  35.0  1.0       2.0         0

逆运算,将数值特征转换为文本特征

In [57]:
h = feature.inverse_transform(feature_)

data1_.iloc[:,1:3] = h
data1_.head()

preprocessing.OneHotEncoder:独热编码，创建哑变量

In [34]:
data1.head()

Age     Sex Embarked  Survived
0  22.0    male        S         0
1  38.0  female        C         2
2  26.0  female        S         2
3  35.0  female        S         2
4  35.0    male        S         0

In [36]:
from sklearn.preprocessing import OneHotEncoder

In [37]:
X = data1.iloc[:,1:-1]  #文字特征：sex和embarked
enc = OneHotEncoder(categories="auto").fit_transform(X)
result= enc.toarray()
result

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [79]:
X.shape

(889, 1)

想看看，toarray()的作用

In [63]:
enc = OneHotEncoder(categories="auto").fit(X)
enc_ = enc.transform(X)
result = enc_.toarray()
result

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [38]:
result.shape

(891, 5)

In [39]:
data1.head()

Age     Sex Embarked  Survived
0  22.0    male        S         0
1  38.0  female        C         2
2  26.0  female        S         2
3  35.0  female        S         2
4  35.0    male        S         0

In [40]:
newdata = pd.concat([data1,pd.DataFrame(result)],axis=1) #axis=1左右相连
newdata.head()

Age     Sex Embarked  Survived    0    1    2    3    4
0  22.0    male        S         0  0.0  1.0  0.0  0.0  1.0
1  38.0  female        C         2  1.0  0.0  1.0  0.0  0.0
2  26.0  female        S         2  1.0  0.0  0.0  0.0  1.0
3  35.0  female        S         2  1.0  0.0  0.0  0.0  1.0
4  35.0    male        S         0  0.0  1.0  0.0  0.0  1.0

现在对dataframe删除某些列来看看

In [41]:
newdata.drop(["Sex","Embarked"],axis=1,inplace=True)
newdata.head()

Age  Survived    0    1    2    3    4
0  22.0         0  0.0  1.0  0.0  0.0  1.0
1  38.0         2  1.0  0.0  1.0  0.0  0.0
2  26.0         2  1.0  0.0  0.0  0.0  1.0
3  35.0         2  1.0  0.0  0.0  0.0  1.0
4  35.0         0  0.0  1.0  0.0  0.0  1.0

In [42]:
newdata.columns = ["Age","Survived","Famle","Male","Embarked_C","Embarked_Q","Embarked_S"]
newdata.head()

Age  Survived  Famle  Male  Embarked_C  Embarked_Q  Embarked_S
0  22.0         0    0.0   1.0         0.0         0.0         1.0
1  38.0         2    1.0   0.0         1.0         0.0         0.0
2  26.0         2    1.0   0.0         0.0         0.0         1.0
3  35.0         2    1.0   0.0         0.0         0.0         1.0
4  35.0         0    0.0   1.0         0.0         0.0         1.0

总结：ValueError: could not convert string to float: 'Q'这个是常出现的问题，主要是scikit-learn的版本有问题，使得这个模块并不能处理string!!!!!
解决：需要更新sklearn

# 将连续型变量划分为分类变量的类

In [43]:
from sklearn.preprocessing import KBinsDiscretizer
X = data1.iloc[:,0].values.reshape(-1,1)

In [55]:
#分为3类，编码方式为ordinal，等宽分箱
est = KBinsDiscretizer(n_bins=3,encode="ordinal",strategy="uniform").fit_transform(X)
# est

In [51]:
type(est)

numpy.ndarray

In [52]:
est.shape

(891, 1)

.ravel()  就是将二维（多维）数组拉直

In [56]:
set(est.ravel())  #查看集合中有几个不一样的标签

{0.0, 1.0, 2.0}

In [59]:
#分为3类，编码方式为onehot，等宽分箱
est = KBinsDiscretizer(n_bins=3,encode="onehot",strategy="uniform").fit_transform(X).toarray()
est

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [60]:
#分为5类，编码方式为onehot，聚类分箱
est = KBinsDiscretizer(n_bins=5,encode="onehot",strategy="kmeans").fit_transform(X).toarray()
est

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

# 3.特征选择

In [1]:
import pandas as pd 
data = pd.read_csv("E:/ivy_machine_learning/program/莫烦学习/2019年寒假学习+sklearn+jupyter用法/菜菜sklearn完整版/digit recognizor.csv")
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [2]:
X = data.iloc[:,1:]
y = data.iloc[:,0]
print(X.shape,y.shape)

(42000, 784) (42000,)


## 3.1 filter 过滤法
### 3.1.1 方差过滤法

In [3]:
from sklearn.feature_selection import VarianceThreshold

In [4]:
X_var0 = VarianceThreshold().fit_transform(X)
X_var0.shape

(42000, 708)

默认阈值是0，过滤了近80个特征（说明这些特征不含任何信息）

如果我们想要过滤掉一半的特征，那我们可以将阈值设置为方差的中位数

In [7]:
import numpy as np
x_fvar = VarianceThreshold(np.median(X.var().values)).fit_transform(X)
x_fvar.shape

(42000, 392)

#### 方差过滤对模型的影响

KNN VS RandomForest 在不同方差过滤下效果的对比

In [10]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
import numpy as np

In [12]:
cross_val_score(RandomForestClassifier(n_estimators=10,random_state=0),X,y,cv=5).mean()

0.9380003861799541

In [11]:
cross_val_score(RandomForestClassifier(n_estimators=10,random_state=0),x_fvar,y,cv=5).mean()

0.9388098166696807

KNN方差过滤前后对比

In [ ]:
%%timeit
knn_score1 = cross_val_score(KNeighborsClassifier(),X,y,cv=5).mean()
print(knn_score1)

### 3.1.2 相关性过滤
判断特征和标签之间的相关性：卡方，F检验，互信息

In [6]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [8]:
# 假设我们需要300个特征
x_fschi = SelectKBest(chi2,k=300).fit_transform(X,y)
x_fschi.shape

(42000, 300)

In [9]:
cross_val_score(RandomForestClassifier(n_estimators=10,random_state=0),x_fschi,y,cv=5).mean()

0.933476037387245

这个相比之前的392个特征，结果变低了，说明过滤掉了一些有效特征，所以这个参数K的选择比较重要。可以通过学习曲线去找合适的k

也可以看P值选k